rules:
  # Colors
  color-named: never
  color-no-hex: true

  # Fonts
  font-family-name-quotes: always-where-recommended
  font-family-no-duplicate-names: true
  font-weight-notation: numeric

  # Functions
  function-blacklist:
  - [mix, red, green, blue, rgb, rgba, lighten, darken]
  - message: "Please use Matter's m_color() function instead"
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: always-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: never-multi-line
  function-parentheses-space-inside: never
  function-url-no-scheme-relative: true
  function-url-quotes: always
  function-whitespace-after: always

  # Strings
  string-no-newline: true
  string-quotes: double

  # Numbers
  number-leading-zero: always
  number-max-precision: null
  number-no-trailing-zeros: true

  # Time
  time-min-milliseconds: 100

  # Units
  unit-case: lower
  unit-no-unknown: true

  # Values
  value-keyword-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true

  # Properties
  custom-property-empty-line-before: always
  custom-property-pattern: null
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  shorthand-property-no-redundant-values: true

  # Declarations
  keyframe-declaration-no-important: true
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: 0
  declaration-block-trailing-semicolon: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: null
  declaration-no-important: true

  # Blocks
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: null
  block-closing-brace-space-before: null
  block-no-empty: true
  block-opening-brace-newline-after: null
  block-opening-brace-newline-before: null
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always

  # Selectors
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-class-pattern:
  - ([a-z\-\_]+)
  - resolveNestedSelectors: true
  - message: "Class must contain only lowercase letters, hypens, and underscores"
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-id-pattern: null
  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  selector-max-attribute: null
  selector-max-class: null
  selector-max-combinators: null
  selector-max-compound-selectors: null
  selector-max-empty-lines: 0
  selector-max-id: 0
  selector-max-specificity: null
  selector-max-type: null
  selector-max-universal: 1
  selector-nested-pattern: null
  selector-no-qualifying-type:
  - true
  - ignore: [attribute, class]
  selector-no-vendor-prefix: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  selector-type-no-unknown:
  - true
  - ignore: custom-elements
  - ignoreTypes: /^n-/
  - message: "Custom elements must start with 'n-'"

  # Media
  custom-media-pattern: null
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: never-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never

  # At-rule
  at-rule-empty-line-before:
  - always
  - except: [after-same-name, first-nested]
  - ignore: [after-comment]
  at-rule-name-case: lower
  at-rule-name-newline-after: always-multi-line
  at-rule-name-space-after: always
  at-rule-no-unknown:
  - true
  - ignoreAtRules: ["extend", "include"]
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never

  # Comments
  comment-empty-line-before:
  - always
  - except: ["first-nested"]
  - ignore: ["after-comment", "stylelint-commands"]
  comment-no-empty: true
  comment-whitespace-inside: always

  # Disallows
  no-descending-specificity: null
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: null
  no-missing-end-of-source-newline: true
  no-unknown-animations: true

  # Misc
  indentation: tab
  length-zero-no-unit: true
  max-empty-lines: 1
  max-line-length: null
  max-nesting-depth:
  - 2
  - ignore: ["blockless-at-rules"]
  rule-empty-line-before:
  - always
  - except: [after-single-line-comment, first-nested]
